/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2021 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
/* Generated By:JavaCC: Do not edit this line. CCJSqlParserVisitor.java Version 7.0.10 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserVisitor {
    public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=2f58de7c587dc1563a175df7a43380fb (do not edit this line) */
