/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2021 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
/* Generated By:JavaCC: Do not edit this line. StringProvider.java Version 7.0 */
/* JavaCCOptions:KEEP_LINE_COLUMN=true */
package net.sf.jsqlparser.parser;


import java.io.IOException;

public class StringProvider implements Provider {

    String _string;
    int _position = 0;
    int _size;

    public StringProvider(String string) {
        _string = string;
        _size = string.length();
    }

    /**
     * 将_string中的从off开始读取len长度的字符，放入cbuf中
     * @param cbuf 存放结果字符
     * @param off 开始读取的位置
     * @param len 读取的最大字符长度
     * @return
     * @throws IOException
     */
    @Override
    public int read(char[] cbuf, int off, int len) throws IOException {
        int numCharsOutstandingInString = _size - _position;

        if (numCharsOutstandingInString == 0) {
            return -1;
        }

        int numBytesInBuffer = cbuf.length;
        int numBytesToRead = numBytesInBuffer - off;
        numBytesToRead = numBytesToRead > len ? len : numBytesToRead;

        if (numBytesToRead > numCharsOutstandingInString) {
            numBytesToRead = numCharsOutstandingInString;
        }

        _string.getChars(_position, _position + numBytesToRead, cbuf, off);

        _position += numBytesToRead;

        return numBytesToRead;
    }

    @Override
    public void close() throws IOException {
        _string = null;
    }

    public static void main(String[] args) throws IOException {
        StringProvider stringProvider = new StringProvider("My name is john, your name is alice");
        char[] res1 = new char[10];
        stringProvider.read(res1, 0, 10);
        //My name is
        System.out.println(new String(res1));

        char[] res2 = new char[10];
        stringProvider.read(res2, 0, 10);
        // john, you
        System.out.println(new String(res2));

    }


}
/* JavaCC - OriginalChecksum=378309cdcf0d00ac5d27d6c7a2b4f010 (do not edit this line) */
